// GENERATED by `hatch run gen-types` (host/src/aurasync/contract_types.py). Do not edit.
// The shapes of the service's contract that the panel's web application reads
// (d-7c8794-6da524). tests/test_contract_types.py fails when this file is stale.

export const CONTRACT_VERSION = 1;

export type ParamKind = "float" | "int" | "bool" | "choice";
export type ParamScope = "global" | "speaker";
export type ApplyKind = "live" | "cut" | "restart";
export type ParamStore = "chain" | "installation" | "session";
export type Applied = "live" | "cut" | "restart" | "none";
export type ParamValue = number | boolean | string;
export type MetricValue = number | boolean | string | null | Record<string, number | null>;

/** `code` is one of control.HTTP_STATUS's; the panel shows `message` and never branches on it. */
export interface ContractError {
  code: string;
  message: string;
}

/** Every reply: `result` when `ok`, `error` when not. */
export type Reply<T> =
  | { v: number; ok: true; result: T; id?: unknown }
  | { v: number; ok: false; error: ContractError; id?: unknown };

export interface ChainParam {
  id: string;
  title: string;
  summary: string;
  help: string;
  kind: ParamKind;
  default: ParamValue;
  low: number | null;
  high: number | null;
  step: number | null;
  unit: string;
  choices: string[];
  scope: ParamScope;
  apply: ApplyKind;
  store: ParamStore;
  implemented: boolean;
}

export interface ChainAlgorithm {
  id: string;
  title: string;
  summary: string;
  help: string;
  cost: string;
  latency_ms: number;
  implemented: boolean;
  available: boolean;
  unavailable_reason: string | null;
  notice: string | null;
  params: ChainParam[];
}

export interface ChainStageValue {
  algorithm: string;
  params: Record<string, ParamValue>;
  speakers: Record<string, Record<string, ParamValue>>;
}

/** What the listener chose, sparse. */
export interface ChainChoice {
  algorithm?: string;
  params?: Record<string, ParamValue>;
  speakers?: Record<string, Record<string, ParamValue>>;
}

export interface ChainStage {
  id: string;
  title: string;
  summary: string;
  help: string;
  algorithm_apply: ApplyKind;
  algorithms: ChainAlgorithm[];
  default_algorithm: string;
  value: ChainStageValue;
  chosen: ChainChoice;
  pending: boolean;
}

export interface ChainDescription {
  stages: ChainStage[];
  latency_ms: number;
}

/** The result of `chain_set` and `chain_reset`. */
export interface ChainChangeReply {
  sequence: number;
  stage: string;
  value: ChainStageValue;
  apply: Applied;
}

/** One stage's live numbers (the stream's `chain` event): `pending` plus whatever the
 * stage reports (typed as `MetricValue`, see `EXTRA_ITEMS`).
 */
export interface StageMetrics {
  pending: boolean;
  [key: string]: MetricValue;
}

export interface QualityInput {
  m: number | null;
  s: number | null;
  i: number | null;
  tp: number | null;
  psr: number | null;
}

export interface QualityOutput {
  m: number | null;
  s: number | null;
  tp: number | null;
  psr: number | null;
  limiter_pct: number | null;
  flattening: boolean;
}

export interface QualitySum {
  m: number | null;
  s: number | null;
}

export interface QualityEvent {
  input: QualityInput;
  outputs: Record<string, QualityOutput>;
  sum: QualitySum;
  net_gain_lu: number | null;
  chain_gain_lu: number | null;
  flattening: boolean;
  flattening_outputs: string[];
  tp_max: number | null;
  limiter_pct_max: number | null;
  cost_ms: number;
}

export interface RadioSpeaker {
  identified: boolean;
  address: string | null;
  sinks: string[];
  bitpool: number | null;
  bitpool_max: number | null;
  bitpool_median_60s: number | null;
  drops_total: number;
  drops_60s: number;
  drops_per_min: number | null;
  last_drop_s: number | null;
  write_mtu: number | null;
}

export interface RadioEvent {
  available: boolean;
  reason: string | null;
  since_s?: number;
  lines?: number;
  speakers: Record<string, RadioSpeaker>;
  drops_seen: number;
  simulated?: boolean;
}

/** `state.radio_log`, and the result of `radio_log` (which has no `available` nor
 * `changes_file`: it is only sent where the level can be changed).
 */
export interface RadioLogStatus {
  available?: boolean;
  active: boolean;
  mode: "light" | "heavy" | null;
  pending: boolean;
  error: string | null;
  heavy?: boolean;
  previous?: string | null;
  verified?: boolean | null;
  changes_file?: string | null;
}

export interface AbLoudness {
  a: number | null;
  b: number | null;
  diff: number | null;
}

export interface AbView {
  a: string;
  b: string;
  active?: boolean;
  match_loudness: boolean;
  loudness_lu: AbLoudness;
  compensation_db: Record<string, number>;
}

/** The residual misalignment the recalibration loop measured last (spec §7.3.4). */
export interface SyncView {
  residual_ms: number | null;
  measured_at: string | null;
  age_s: number | null;
  speakers: string[];
}

export interface SpeakerView {
  name: string;
  sink: string | null;
  muted: boolean;
  playing: boolean;
  output: "virtual" | "absent" | "playing" | "lost" | null;
  output_kind: "virtual" | "bluetooth" | "wired";
  rejoin: "trying" | "gave_up" | null;
  address: string | null;
  battery_pct: number | null;
  codec: string | null;
  rssi_dbm: number | null;
  modalias: string | null;
}

export interface SessionView {
  status: string;
}

export interface LatencyView {
  known_ms: number;
  measured_ms: number | null;
}

export interface HealthView {
  streams_open: number;
}

export interface VolumeAvrcp {
  state: "off" | "entering" | "on" | "leaving" | "failed";
  pending: boolean;
  error: string | null;
}

export interface StateView {
  sequence: number;
  session: SessionView;
  speakers: SpeakerView[];
  latency: LatencyView;
  health: HealthView;
  chain_summary: Record<string, string>;
  chain_latency_ms: number;
  chain_pending: string[];
  quality: QualityEvent | null;
  radio: RadioEvent;
  radio_log: RadioLogStatus;
  volume_avrcp: VolumeAvrcp;
  ab: AbView | null;
  sync: SyncView;
}

/** The stream's `chain` event: each stage's live numbers, by stage id. */
export type ChainMetricsEvent = Record<string, StageMetrics>;

/** The stream's events this application reads, and their `data`. */
export interface StreamEvents {
  state: StateView;
  quality: QualityEvent;
  chain: ChainMetricsEvent;
  radio: RadioEvent;
}

/** `set` with a speaker: its `changes` (control.SPEAKER_FIELDS). */
export type SpeakerChanges = { pan?: number; ambience?: number; gain_db?: number; delay_ms?: number; muted?: boolean; kind?: "generic" | "go4" | "charge6"; role_kind?: "principal" | "ambient"; eq_db?: number[] | null; };
/** `set` without a speaker: its `changes` (control.GLOBAL_FIELDS). */
export type GlobalChanges = { rear_delay_ms?: number; volume_db?: number; extract_ambience?: boolean; decorrelate?: boolean; layout?: "quad" | "lcrs" | "5.0" | "hex" | "7.0" | "octagon" | "rings" | "auto"; block_size?: 1024 | 2048 | 4096 | 8192; player_latency_ms?: number; sink_description?: string; recalibrate_every_s?: number; recalibrate_measure_s?: number; output_mode?: "combinado" | "separado"; eq_active?: boolean; recalibrate?: boolean; probe?: boolean; probe_margin_db?: number; };

/** The operations this application sends to `POST /v1/command`, and their arguments (control.OPS). */
export interface OpArgs {
  chain: Record<string, never>;
  chain_set: { stage: string; algorithm?: string; params?: Record<string, unknown>; speaker?: string; };
  chain_reset: { stage: string; param?: string; speaker?: string; };
  radio_log: { active: boolean; mode?: "light" | "heavy"; };
  state: Record<string, never>;
  pair_status: Record<string, never>;
  pair_start: { seconds?: number; };
  pair_approve: { request: string; scope?: "read" | "control" | "admin"; };
  pair_deny: { request: string; };
  clients: Record<string, never>;
  client_revoke: { client: string; };
  client_rename: { client: string; name: string; };
}

export type OpName = keyof OpArgs;

/** The result of the operations whose shape this application reads. */
export interface OpResults {
  chain: ChainDescription;
  chain_set: ChainChangeReply;
  chain_reset: ChainChangeReply;
  radio_log: RadioLogStatus;
}

export type ResultOf<K extends OpName> = K extends keyof OpResults ? OpResults[K] : unknown;
